import { resendDelivery, revokeDelivery } from "@/features/delivery/admin-actions";
import type { AdminOrdersData } from "@/features/orders/admin-repository";

export function AdminOrders({ data, result }: { data: AdminOrdersData; result?: string }) {
  return <main id="main-content" className="px-5 py-8 sm:px-8"><div className="mx-auto max-w-[1500px]"><div className="flex flex-col gap-4 border-b border-white/10 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-muted">Commerce</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.045em]">Orders and delivery</h1><p className="mt-2 max-w-2xl leading-6 text-secondary">Payment reconciliation plus expiring private delivery controls. Resending rotates the private link; revoking disables all active links.</p></div><span className="text-xs text-muted">Latest 100 records</span></div>
    {result && <div role="status" className="mt-6 rounded-xl border border-white/10 bg-white/[0.03] p-4 text-sm text-secondary">{resultMessage(result)}</div>}
    {data.status !== "ready" ? <div className="mt-7 rounded-xl border border-dashed border-white/15 p-6 text-secondary">{data.status === "unconfigured" ? "Connect Supabase and apply the Phase 6-7 migrations to view orders." : "Order data could not be verified."}</div> : data.orders.length === 0 ? <div className="mt-7 rounded-xl border border-dashed border-white/15 p-6 text-secondary">No customer orders exist yet.</div> : <div className="mt-7 overflow-x-auto rounded-xl border border-white/10"><table className="min-w-[1180px] w-full text-left text-sm"><thead className="bg-white/[0.03] text-xs uppercase tracking-[0.08em] text-muted"><tr><th className="p-4">Order</th><th className="p-4">System</th><th className="p-4">Customer</th><th className="p-4">Amount</th><th className="p-4">Payment</th><th className="p-4">Delivery</th><th className="p-4">Created</th><th className="p-4">Controls</th></tr></thead><tbody>{data.orders.map((order) => <tr key={order.id} className="border-t border-white/10 align-top"><td className="p-4 font-semibold">{order.orderNumber}</td><td className="p-4"><span className="font-semibold">{order.productName}</span><span className="mt-1 block text-xs text-muted">v{order.versionLabel}</span></td><td className="p-4"><span>{order.customerName}</span><span className="mt-1 block text-xs text-muted">{order.customerEmail}</span></td><td className="p-4">{formatMoney(order.totalMinor, order.currency)}</td><td className="p-4"><Status value={order.status} /></td><td className="p-4">{order.delivery ? <><Status value={order.delivery.status} /><span className="mt-2 block text-xs leading-5 text-muted">Attempt {order.delivery.attemptCount}{order.delivery.maxDownloads > 0 ? ` · ${order.delivery.downloadCount}/${order.delivery.maxDownloads} downloads` : ""}</span></> : <span className="text-muted">Not created</span>}</td><td className="p-4 text-secondary">{formatDate(order.createdAt)}</td><td className="p-4"><div className="flex flex-wrap gap-2">{order.status === "paid" && order.delivery && order.delivery.status !== "revoked" && <form action={resendDelivery.bind(null, order.id)}><button className="min-h-9 rounded-lg border border-white/15 px-3 text-xs font-semibold hover:bg-white/[0.04]">Resend</button></form>}{order.delivery && order.delivery.status !== "revoked" && <form action={revokeDelivery.bind(null, order.id)}><button className="min-h-9 rounded-lg border border-red-400/25 px-3 text-xs font-semibold text-red-200 hover:bg-red-400/[0.06]">Revoke</button></form>}</div></td></tr>)}</tbody></table></div>}
  </div></main>;
}

function Status({ value }: { value: string }) { const tone = ["paid", "delivered"].includes(value) ? "border-emerald-400/30 text-emerald-200" : ["pending", "processing"].includes(value) ? "border-amber-400/30 text-amber-100" : "border-white/15 text-secondary"; return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold capitalize ${tone}`}>{value}</span>; }
function formatMoney(value: number, currency: string) { return new Intl.NumberFormat("en-PH", { style: "currency", currency }).format(value / 100); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Manila" }).format(new Date(value)); }
function resultMessage(result: string) { if (result === "sent") return "A new private delivery link was emailed and the previous link was revoked."; if (result === "revoked") return "Delivery access was revoked."; if (result === "email_unavailable") return "The link was rotated, but Resend is not configured. No email was sent."; if (result === "unchanged") return "The order was not eligible for another delivery attempt."; return "The delivery operation could not be completed safely."; }