"use client";

import { useActionState } from "react";
import { updateCompanyProfile, type CompanyProfileEditorState } from "@/features/content/company-profile-actions";
import type { AdminCompanyProfileData } from "@/features/content/company-profile-types";

const initialState: CompanyProfileEditorState = { status: "idle" };
const inputClass = "min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50/50 px-3.5 text-sm font-medium text-slate-900 focus:border-blue-600 focus:bg-white focus:outline-none transition-all";
const textareaClass = `${inputClass} min-h-32 py-3 leading-6`;
const buttonClass = "inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-200 bg-white px-4 text-xs font-semibold text-slate-900 hover:bg-slate-50 shadow-2xs disabled:cursor-not-allowed disabled:text-slate-400 transition-all";

export function AdminCompanyProfileSection({ data }: { data: AdminCompanyProfileData }) {
  const [state, action, pending] = useActionState(updateCompanyProfile, initialState);
  const profile = data.profile;
  return (
    <section id="company-profile" aria-labelledby="company-profile-title" className="mt-12 scroll-mt-24 border-t border-slate-200/80 pt-10">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">Available module</p><h2 id="company-profile-title" className="mt-2 text-2xl font-bold tracking-tight text-slate-900">Company and public contact profile</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 font-medium">Manage approved brand summaries and optional public contact channels without implying registration, an office, or a larger team.</p></div><StatusBadge status={data.status === "ready" ? profile.status : data.status} /></div>
      <form action={action} className="mt-6 grid gap-6 xl:grid-cols-[320px_minmax(0,1fr)]">
        <aside className="self-start rounded-2xl border border-slate-200/80 bg-white p-6 shadow-xs"><p className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">Locked identity</p><dl className="mt-5 grid gap-5"><div><dt className="text-xs text-slate-500 font-medium">Brand</dt><dd className="mt-1 font-bold text-slate-900">{profile.brandName}</dd></div><div><dt className="text-xs text-slate-500 font-medium">Founder</dt><dd className="mt-1 font-bold text-slate-900">{profile.founderName}</dd></div><div><dt className="text-xs text-slate-500 font-medium">Public title</dt><dd className="mt-1 font-bold text-slate-900">{profile.founderTitle}</dd></div></dl><p className="mt-6 border-t border-slate-100 pt-5 text-xs leading-5 text-slate-500 font-medium">These confirmed identity fields are intentionally not editable from routine content management.</p></aside>
        <div className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-xs"><input type="hidden" name="updatedAt" value={profile.updatedAt} /><div className="grid gap-5"><Field label="Approved company summary" error={state.fieldErrors?.companySummary}><textarea name="companySummary" defaultValue={profile.companySummary} className={textareaClass} /></Field><Field label="Founder biography" error={state.fieldErrors?.founderBio}><textarea name="founderBio" defaultValue={profile.founderBio} className={textareaClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Public email (optional)" error={state.fieldErrors?.publicEmail}><input name="publicEmail" type="email" defaultValue={profile.publicEmail ?? ""} className={inputClass} placeholder="Confirmed public address" /></Field><Field label="Public phone (optional)" error={state.fieldErrors?.publicPhone}><input name="publicPhone" type="tel" defaultValue={profile.publicPhone ?? ""} className={inputClass} placeholder="Confirmed public number" /></Field></div><p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900 font-medium">Only enter channels the owner has approved for direct public display. Transactional email remains a separate provider configuration.</p></div><div className="mt-6 flex flex-wrap gap-3"><button name="intent" value="save" disabled={pending} className={buttonClass}>{pending ? "Saving..." : "Save changes"}</button><button name="intent" value="publish" disabled={pending} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-slate-900 px-4 text-xs font-semibold text-white shadow-sm hover:bg-slate-800 transition-colors">{profile.status === "archived" ? "Restore and publish" : profile.status === "published" ? "Keep published" : "Publish profile"}</button>{profile.status !== "archived" && <button name="intent" value="archive" disabled={pending} className="min-h-11 rounded-xl border border-red-200 bg-red-50 px-4 text-xs font-semibold text-red-700 hover:bg-red-100 transition-colors">Archive public profile</button>}</div><StatusNotice state={state} dataStatus={data.status} /></div>
      </form>
    </section>
  );
}

function Field({ label, error, children }: { label: string; error?: string[]; children: React.ReactNode }) { return <label className="grid gap-2 text-xs font-bold text-slate-700"><span>{label}</span>{children}{error?.[0] && <span className="font-semibold text-red-600">{error[0]}</span>}</label>; }
function StatusBadge({ status }: { status: string }) { return <span className="inline-flex w-fit rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-bold capitalize text-slate-700">{status}</span>; }
function StatusNotice({ state, dataStatus }: { state: CompanyProfileEditorState; dataStatus: AdminCompanyProfileData["status"] }) { if (state.status !== "idle" && state.message) return <p role="alert" className={`mt-4 rounded-2xl border p-3 text-xs leading-5 font-semibold ${state.status === "unavailable" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-red-200 bg-red-50 text-red-900"}`}>{state.message}</p>; if (dataStatus === "unconfigured") return <p className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 font-semibold text-amber-900">The approved baseline is shown locally. Connect Supabase before saving persistent changes.</p>; if (dataStatus === "error") return <p className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-3 text-xs leading-5 font-semibold text-red-900">The stored company profile could not be verified, so only the approved baseline is shown.</p>; return null; }