"use client";

import { useActionState } from "react";
import { updateCompanyProfile, type CompanyProfileEditorState } from "@/features/content/company-profile-actions";
import type { AdminCompanyProfileData } from "@/features/content/company-profile-types";

const initialState: CompanyProfileEditorState = { status: "idle" };
const inputClass = "min-h-11 w-full rounded-lg border border-white/15 bg-background px-3 text-sm text-foreground placeholder:text-muted focus:border-brand focus:outline-none";
const textareaClass = `${inputClass} min-h-32 py-3 leading-6`;
const buttonClass = "inline-flex min-h-11 items-center justify-center rounded-lg border border-white/15 px-4 text-xs font-semibold text-foreground hover:bg-white/[0.04] disabled:cursor-not-allowed disabled:text-muted";

export function AdminCompanyProfileSection({ data }: { data: AdminCompanyProfileData }) {
  const [state, action, pending] = useActionState(updateCompanyProfile, initialState);
  const profile = data.profile;
  return (
    <section id="company-profile" aria-labelledby="company-profile-title" className="mt-12 scroll-mt-24 border-t border-white/10 pt-10">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-muted">Available module</p><h2 id="company-profile-title" className="mt-2 text-2xl font-semibold tracking-[-0.035em]">Company and public contact profile</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-secondary">Manage approved brand summaries and optional public contact channels without implying registration, an office, or a larger team.</p></div><StatusBadge status={data.status === "ready" ? profile.status : data.status} /></div>
      <form action={action} className="mt-6 grid gap-6 xl:grid-cols-[320px_minmax(0,1fr)]">
        <aside className="self-start rounded-xl border border-white/10 bg-surface p-5"><p className="text-xs font-semibold uppercase tracking-[0.1em] text-muted">Locked identity</p><dl className="mt-5 grid gap-5"><div><dt className="text-xs text-muted">Brand</dt><dd className="mt-1 font-semibold">{profile.brandName}</dd></div><div><dt className="text-xs text-muted">Founder</dt><dd className="mt-1 font-semibold">{profile.founderName}</dd></div><div><dt className="text-xs text-muted">Public title</dt><dd className="mt-1 font-semibold">{profile.founderTitle}</dd></div></dl><p className="mt-6 border-t border-white/10 pt-5 text-xs leading-5 text-muted">These confirmed identity fields are intentionally not editable from routine content management.</p></aside>
        <div className="rounded-xl border border-white/10 bg-surface p-5 sm:p-6"><input type="hidden" name="updatedAt" value={profile.updatedAt} /><div className="grid gap-5"><Field label="Approved company summary" error={state.fieldErrors?.companySummary}><textarea name="companySummary" defaultValue={profile.companySummary} className={textareaClass} /></Field><Field label="Founder biography" error={state.fieldErrors?.founderBio}><textarea name="founderBio" defaultValue={profile.founderBio} className={textareaClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Public email (optional)" error={state.fieldErrors?.publicEmail}><input name="publicEmail" type="email" defaultValue={profile.publicEmail ?? ""} className={inputClass} placeholder="Confirmed public address" /></Field><Field label="Public phone (optional)" error={state.fieldErrors?.publicPhone}><input name="publicPhone" type="tel" defaultValue={profile.publicPhone ?? ""} className={inputClass} placeholder="Confirmed public number" /></Field></div><p className="rounded-lg border border-amber-300/15 bg-amber-300/[0.04] p-4 text-xs leading-5 text-amber-100">Only enter channels the owner has approved for direct public display. Transactional email remains a separate provider configuration.</p></div><div className="mt-6 flex flex-wrap gap-3"><button name="intent" value="save" disabled={pending} className={buttonClass}>{pending ? "Saving..." : "Save changes"}</button><button name="intent" value="publish" disabled={pending} className={`${buttonClass} bg-foreground text-background hover:bg-white`}>{profile.status === "archived" ? "Restore and publish" : profile.status === "published" ? "Keep published" : "Publish profile"}</button>{profile.status !== "archived" && <button name="intent" value="archive" disabled={pending} className={`${buttonClass} text-red-300 hover:text-red-200`}>Archive public profile</button>}</div><StatusNotice state={state} dataStatus={data.status} /></div>
      </form>
    </section>
  );
}

function Field({ label, error, children }: { label: string; error?: string[]; children: React.ReactNode }) { return <label className="grid gap-2 text-xs font-semibold text-secondary"><span>{label}</span>{children}{error?.[0] && <span className="font-normal text-red-300">{error[0]}</span>}</label>; }
function StatusBadge({ status }: { status: string }) { return <span className="inline-flex w-fit rounded-full border border-white/10 px-3 py-1 text-xs capitalize text-secondary">{status}</span>; }
function StatusNotice({ state, dataStatus }: { state: CompanyProfileEditorState; dataStatus: AdminCompanyProfileData["status"] }) { if (state.status !== "idle" && state.message) return <p role="alert" className={`mt-4 rounded-lg border p-3 text-xs leading-5 ${state.status === "unavailable" ? "border-amber-300/20 bg-amber-300/[0.06] text-amber-100" : "border-red-300/20 bg-red-300/[0.06] text-red-100"}`}>{state.message}</p>; if (dataStatus === "unconfigured") return <p className="mt-4 rounded-lg border border-amber-300/20 bg-amber-300/[0.06] p-3 text-xs leading-5 text-amber-100">The approved baseline is shown locally. Connect Supabase before saving persistent changes.</p>; if (dataStatus === "error") return <p className="mt-4 rounded-lg border border-red-300/20 bg-red-300/[0.06] p-3 text-xs leading-5 text-red-100">The stored company profile could not be verified, so only the approved baseline is shown.</p>; return null; }