"use client";

import { useActionState, useMemo, useState } from "react";
import { createTestimonialDraft, updateTestimonial, type TestimonialEditorState } from "@/features/content/testimonial-actions";
import type { AdminTestimonialData, TestimonialItem } from "@/features/content/testimonial-types";

const initialState: TestimonialEditorState = { status: "idle" };
const inputClass = "min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50/50 px-3.5 text-sm font-medium text-slate-900 focus:border-blue-600 focus:bg-white focus:outline-none transition-all";
const textareaClass = `${inputClass} min-h-28 py-3 leading-6`;
const buttonClass = "inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-200 bg-white px-4 text-xs font-semibold text-slate-900 hover:bg-slate-50 shadow-2xs disabled:cursor-not-allowed disabled:text-slate-400 transition-all";

export function AdminTestimonialSection({ data }: { data: AdminTestimonialData }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const items = useMemo(() => { const search = query.trim().toLowerCase(); return data.items.filter((item) => (!search || `${item.attributionName} ${item.attributionOrganization ?? ""} ${item.quote}`.toLowerCase().includes(search)) && (status === "all" || item.status === status)); }, [data.items, query, status]);
  const published = data.items.filter((item) => item.status === "published").length;
  const drafts = data.items.filter((item) => item.status === "draft").length;
  const verified = data.items.filter((item) => item.permissionConfirmedAt !== null).length;

  return (
    <section id="testimonials" aria-labelledby="testimonial-management-title" className="mt-12 scroll-mt-24 border-t border-slate-200/80 pt-10">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">Available module</p><h2 id="testimonial-management-title" className="mt-2 text-2xl font-bold tracking-tight text-slate-900">Verified testimonials</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 font-medium">Keep source evidence private, record explicit publication permission, and publish only authentic customer statements.</p></div><p className="text-xs text-slate-500 font-medium">No testimonials are prefilled or generated.</p></div>
      <div className="mt-5 grid gap-px overflow-hidden rounded-2xl border border-slate-200/80 bg-slate-200/60 sm:grid-cols-3 lg:max-w-2xl shadow-xs"><Metric label="Published" value={published} /><Metric label="Private drafts" value={drafts} /><Metric label="Permission confirmed" value={verified} /></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[420px_minmax(0,1fr)]">
        <CreateForm />
        <div><div className="grid gap-3 rounded-t-2xl border border-slate-200/80 bg-white p-4 md:grid-cols-[minmax(220px,1fr)_170px]"><label className="grid gap-2 text-xs font-bold text-slate-700"><span>Search testimonials</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Customer, organization, or statement" className={inputClass} /></label><Filter value={status} onChange={setStatus} /></div><div className="overflow-hidden rounded-b-2xl border-x border-b border-slate-200/80 bg-white shadow-xs">{items.length > 0 ? <div className="divide-y divide-slate-100">{items.map((item) => <Editor key={`${item.id}-${item.updatedAt}`} item={item} />)}</div> : <EmptyState status={data.status} filtered={data.items.length > 0} />}</div></div>
      </div>
    </section>
  );
}

function CreateForm() {
  const [state, action, pending] = useActionState(createTestimonialDraft, initialState);
  return <form action={action} className="self-start rounded-2xl border border-slate-200/80 bg-white p-6 shadow-xs"><h3 className="text-lg font-bold text-slate-900">Create testimonial draft</h3><p className="mt-2 text-xs leading-5 text-slate-500 font-medium">The statement stays private until its source and permission are reviewed.</p><Fields state={state} /><button type="submit" disabled={pending} className="mt-5 w-full inline-flex min-h-11 items-center justify-center rounded-xl bg-slate-900 px-4 text-xs font-semibold text-white shadow-sm hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50 transition-colors">{pending ? "Creating..." : "Create private draft"}</button><StatusNotice state={state} /></form>;
}

function Editor({ item }: { item: TestimonialItem }) {
  const [state, action, pending] = useActionState(updateTestimonial.bind(null, item.id), initialState);
  return <details className="group" open={item.status === "draft"}><summary className="grid cursor-pointer list-none gap-3 px-5 py-5 marker:hidden sm:grid-cols-[minmax(0,1fr)_120px_90px] sm:items-center hover:bg-slate-50 transition-colors"><div className="min-w-0"><p className="truncate font-bold text-slate-900">{item.attributionName}</p><p className="mt-1 truncate text-xs text-slate-500 font-medium">{item.permissionConfirmedAt ? "Permission confirmed" : "Permission pending"}{item.isFeatured ? " · featured" : ""}</p></div><span className="text-xs font-bold capitalize text-slate-600">{item.status}</span><span className="text-right text-xs font-bold text-blue-600 group-open:hidden">Edit</span></summary><form action={action} className="border-t border-slate-200/80 bg-slate-50/50 px-5 py-5"><input type="hidden" name="updatedAt" value={item.updatedAt} /><Fields state={state} item={item} /><div className="mt-5 flex flex-wrap gap-3"><button name="intent" value="save" disabled={pending} className={buttonClass}>{pending ? "Saving..." : "Save changes"}</button><button name="intent" value="publish" disabled={pending || !item.permissionConfirmedAt} title={!item.permissionConfirmedAt ? "Confirm permission in the form and save before publishing." : undefined} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-slate-900 px-4 text-xs font-semibold text-white shadow-sm hover:bg-slate-800 transition-colors">{item.status === "archived" ? "Restore and publish" : item.status === "published" ? "Keep published" : "Publish testimonial"}</button>{item.status !== "archived" && <button name="intent" value="archive" disabled={pending} className="min-h-11 rounded-xl border border-red-200 bg-red-50 px-4 text-xs font-semibold text-red-700 hover:bg-red-100 transition-colors">Archive</button>}</div>{!item.permissionConfirmedAt && <p className="mt-3 text-xs font-semibold text-amber-800">Save the confirmed permission record before the publish action becomes available.</p>}<StatusNotice state={state} /></form></details>;
}

function Fields({ state, item }: { state: TestimonialEditorState; item?: TestimonialItem }) {
  return <div className="mt-5 grid gap-4"><Field label="Customer statement" error={state.fieldErrors?.quote}><textarea name="quote" defaultValue={item?.quote} className={`${textareaClass} min-h-36`} placeholder="Paste the customer's exact approved statement." /></Field><Field label="Public attribution name" error={state.fieldErrors?.attributionName}><input name="attributionName" defaultValue={item?.attributionName} className={inputClass} placeholder="Approved public name" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Role (optional)" error={state.fieldErrors?.attributionRole}><input name="attributionRole" defaultValue={item?.attributionRole ?? ""} className={inputClass} /></Field><Field label="Organization (optional)" error={state.fieldErrors?.attributionOrganization}><input name="attributionOrganization" defaultValue={item?.attributionOrganization ?? ""} className={inputClass} /></Field></div><Field label="Relationship context" error={state.fieldErrors?.relationshipContext}><input name="relationshipContext" defaultValue={item?.relationshipContext} className={inputClass} placeholder="How this customer worked with WebSystemBuilders" /></Field><div className="rounded-xl border border-amber-200 bg-amber-50/60 p-4"><Field label="Private verification reference — administrators only" error={state.fieldErrors?.verificationReference}><textarea name="verificationReference" defaultValue={item?.verificationReference} className={`${textareaClass} min-h-24 bg-white`} placeholder="Record the private email, document, or approval reference." /></Field><label className="mt-4 flex items-start gap-3 text-xs font-bold text-slate-700"><input name="permissionConfirmed" type="checkbox" defaultChecked={Boolean(item?.permissionConfirmedAt)} className="mt-0.5 size-4 accent-blue-600" /><span>I confirm the customer explicitly permitted this statement and attribution to be published.</span></label>{state.fieldErrors?.permissionConfirmed?.[0] && <p className="mt-2 text-xs font-semibold text-red-600">{state.fieldErrors.permissionConfirmed[0]}</p>}</div><div className="grid gap-4 sm:grid-cols-[120px_1fr] sm:items-end"><Field label="Order" error={state.fieldErrors?.sortOrder}><input name="sortOrder" type="number" min="0" max="10000" defaultValue={item?.sortOrder ?? 0} className={inputClass} /></Field><label className="flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50/50 px-3.5 text-xs font-bold text-slate-700"><input name="isFeatured" type="checkbox" defaultChecked={item?.isFeatured} className="size-4 accent-blue-600" /><span>Feature on the homepage</span></label></div></div>;
}

function Field({ label, error, children }: { label: string; error?: string[]; children: React.ReactNode }) { return <label className="grid gap-2 text-xs font-bold text-slate-700"><span>{label}</span>{children}{error?.[0] && <span className="font-semibold text-red-600">{error[0]}</span>}</label>; }
function Filter({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="grid gap-2 text-xs font-bold text-slate-700"><span>Status</span><select value={value} onChange={(event) => onChange(event.target.value)} className={inputClass}><option value="all">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label>; }
function StatusNotice({ state }: { state: TestimonialEditorState }) { if (state.status === "idle" || !state.message) return null; return <p role="alert" className={`mt-4 rounded-2xl border p-3 text-xs leading-5 font-semibold ${state.status === "unavailable" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-red-200 bg-red-50 text-red-900"}`}>{state.message}</p>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="bg-white p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold text-slate-900 tabular-nums">{value}</p></div>; }
function EmptyState({ status, filtered }: { status: AdminTestimonialData["status"]; filtered: boolean }) { const title = status === "unconfigured" ? "The database is not connected." : status === "error" ? "Testimonials could not be loaded safely." : filtered ? "No testimonials match these filters." : "No testimonials exist."; const copy = status === "unconfigured" ? "Connect Supabase and apply the testimonial migration before creating persistent records." : status === "error" ? "No partial content or verification evidence is shown while either source cannot be confirmed." : filtered ? "Adjust the search or status filter." : "Create a private draft only when authentic customer feedback and its permission record are available."; return <div className="grid min-h-72 place-items-center px-6 py-12 text-center"><div className="max-w-md"><h3 className="text-lg font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500 font-medium">{copy}</p></div></div>; }
