"use client";

import { useActionState, useMemo, useState } from "react";
import { createSiteContentBlock, updateSiteContentBlock, type SiteContentEditorState } from "@/features/content/site-content-actions";
import type { AdminSiteContentData, SiteContentBlock } from "@/features/content/site-content-types";

const initialState: SiteContentEditorState = { status: "idle" };
const inputClass = "min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50/50 px-3.5 text-sm font-medium text-slate-900 focus:border-blue-600 focus:bg-white focus:outline-none transition-all";
const textareaClass = `${inputClass} min-h-28 py-3 leading-6`;
const buttonClass = "inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-200 bg-white px-4 text-xs font-semibold text-slate-900 hover:bg-slate-50 shadow-2xs disabled:cursor-not-allowed disabled:text-slate-400 transition-all";

export function AdminSiteContentSection({ data }: { data: AdminSiteContentData }) {
  const [placement, setPlacement] = useState("all");
  const [status, setStatus] = useState("all");
  const items = useMemo(() => data.items.filter((item) => (placement === "all" || item.placement === placement) && (status === "all" || item.status === status)), [data.items, placement, status]);
  const published = data.items.filter((item) => item.status === "published").length;
  const drafts = data.items.filter((item) => item.status === "draft").length;
  const archived = data.items.filter((item) => item.status === "archived").length;
  return (
    <section id="site-content" aria-labelledby="site-content-title" className="mt-12 scroll-mt-24 border-t border-slate-200/80 pt-10">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">Available module</p><h2 id="site-content-title" className="mt-2 text-2xl font-bold tracking-tight text-slate-900">Homepage features and announcements</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 font-medium">Publish one announcement and one editorial homepage feature at a time. All actions remain within this website.</p></div><p className="text-xs text-slate-500 font-medium">Draft-first, manual publication, no placeholder claims.</p></div>
      <div className="mt-5 grid gap-px overflow-hidden rounded-2xl border border-slate-200/80 bg-slate-200/60 sm:grid-cols-3 lg:max-w-2xl shadow-xs"><Metric label="Published placements" value={published} /><Metric label="Private drafts" value={drafts} /><Metric label="Archived" value={archived} /></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[420px_minmax(0,1fr)]">
        <CreateForm />
        <div><div className="grid gap-3 rounded-t-2xl border border-slate-200/80 bg-white p-4 sm:grid-cols-2"><Filter label="Placement" value={placement} onChange={setPlacement} options={[["all", "All placements"], ["announcement", "Announcement"], ["homepage_feature", "Homepage feature"]]} /><Filter label="Status" value={status} onChange={setStatus} options={[["all", "All statuses"], ["draft", "Draft"], ["published", "Published"], ["archived", "Archived"]]} /></div><div className="overflow-hidden rounded-b-2xl border-x border-b border-slate-200/80 bg-white shadow-xs">{items.length ? <div className="divide-y divide-slate-100">{items.map((item) => <Editor key={`${item.id}-${item.updatedAt}`} item={item} />)}</div> : <EmptyState status={data.status} filtered={data.items.length > 0} />}</div></div>
      </div>
    </section>
  );
}

function CreateForm() {
  const [state, action, pending] = useActionState(createSiteContentBlock, initialState);
  return <form action={action} className="self-start rounded-2xl border border-slate-200/80 bg-white p-6 shadow-xs"><h3 className="text-lg font-bold text-slate-900">Create content draft</h3><p className="mt-2 text-xs leading-5 text-slate-500 font-medium">New content stays private until an administrator publishes it.</p><Fields state={state} /><button type="submit" disabled={pending} className="mt-5 w-full inline-flex min-h-11 items-center justify-center rounded-xl bg-[#2563EB] px-4 text-xs font-semibold text-white shadow-sm hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50 transition-colors">{pending ? "Creating..." : "Create private draft"}</button><StatusNotice state={state} /></form>;
}

function Editor({ item }: { item: SiteContentBlock }) {
  const [state, action, pending] = useActionState(updateSiteContentBlock.bind(null, item.id), initialState);
  return <details className="group" open={item.status === "draft"}><summary className="grid cursor-pointer list-none gap-3 px-5 py-5 marker:hidden sm:grid-cols-[minmax(0,1fr)_130px_80px] sm:items-center hover:bg-slate-50 transition-colors"><div className="min-w-0"><p className="truncate font-bold text-slate-900">{item.title}</p><p className="mt-1 text-xs text-slate-500 font-medium">{placementLabel(item.placement)}</p></div><span className="text-xs font-bold capitalize text-slate-600">{item.status}</span><span className="text-right text-xs font-bold text-blue-600 group-open:hidden">Edit</span></summary><form action={action} className="border-t border-slate-200/80 bg-slate-50/50 px-5 py-5"><input type="hidden" name="updatedAt" value={item.updatedAt} /><Fields state={state} item={item} /><div className="mt-5 flex flex-wrap gap-3"><button name="intent" value="save" disabled={pending} className={buttonClass}>{pending ? "Saving..." : "Save changes"}</button><button name="intent" value="publish" disabled={pending} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-[#2563EB] px-4 text-xs font-semibold text-white shadow-sm hover:bg-blue-700 transition-colors">{item.status === "archived" ? "Restore and publish" : item.status === "published" ? "Keep published" : "Publish content"}</button>{item.status !== "archived" && <button name="intent" value="archive" disabled={pending} className="min-h-11 rounded-xl border border-red-200 bg-red-50 px-4 text-xs font-semibold text-red-700 hover:bg-red-100 transition-colors">Archive</button>}</div><StatusNotice state={state} /></form></details>;
}

function Fields({ state, item }: { state: SiteContentEditorState; item?: SiteContentBlock }) {
  return <div className="mt-5 grid gap-4"><Field label="Placement" error={state.fieldErrors?.placement}><select name="placement" defaultValue={item?.placement ?? "announcement"} className={inputClass}><option value="announcement">Site-wide announcement</option><option value="homepage_feature">Homepage feature</option></select></Field><Field label="Message or feature title" error={state.fieldErrors?.title}><textarea name="title" defaultValue={item?.title} className={`${textareaClass} min-h-24`} placeholder="Use factual, approved public copy." /></Field><div className="rounded-xl border border-slate-200 bg-slate-50/50 p-4"><p className="text-xs font-bold text-slate-900">Homepage feature fields</p><p className="mt-1 text-xs leading-5 text-slate-500 font-medium">Required for homepage features. Leave both blank for announcements.</p><div className="mt-4 grid gap-4"><Field label="Eyebrow" error={state.fieldErrors?.eyebrow}><input name="eyebrow" defaultValue={item?.eyebrow ?? ""} className={inputClass} placeholder="Short context label" /></Field><Field label="Supporting copy" error={state.fieldErrors?.body}><textarea name="body" defaultValue={item?.body ?? ""} className={textareaClass} placeholder="Verified supporting detail." /></Field></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Action label (optional)" error={state.fieldErrors?.actionLabel}><input name="actionLabel" defaultValue={item?.actionLabel ?? ""} className={inputClass} /></Field><Field label="Internal action path" error={state.fieldErrors?.actionHref}><input name="actionHref" defaultValue={item?.actionHref ?? ""} className={inputClass} placeholder="/systems" /></Field></div><Field label="Order" error={state.fieldErrors?.sortOrder}><input name="sortOrder" type="number" min="0" max="10000" defaultValue={item?.sortOrder ?? 0} className={inputClass} /></Field></div>;
}

function Field({ label, error, children }: { label: string; error?: string[]; children: React.ReactNode }) { return <label className="grid gap-2 text-xs font-bold text-slate-700"><span>{label}</span>{children}{error?.[0] && <span className="font-semibold text-red-600">{error[0]}</span>}</label>; }
function Filter({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<[string, string]> }) { return <label className="grid gap-2 text-xs font-bold text-slate-700"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className={inputClass}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function StatusNotice({ state }: { state: SiteContentEditorState }) { if (state.status === "idle" || !state.message) return null; return <p role="alert" className={`mt-4 rounded-2xl border p-3 text-xs leading-5 font-semibold ${state.status === "unavailable" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-red-200 bg-red-50 text-red-900"}`}>{state.message}</p>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="bg-white p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold text-slate-900 tabular-nums">{value}</p></div>; }
function EmptyState({ status, filtered }: { status: AdminSiteContentData["status"]; filtered: boolean }) { const title = status === "unconfigured" ? "The database is not connected." : status === "error" ? "Site content could not be loaded." : filtered ? "No content matches these filters." : "No site content blocks exist."; const copy = status === "unconfigured" ? "Connect Supabase and apply the site-content migration before managing persistent records." : status === "error" ? "No partial content is shown while the source cannot be verified." : filtered ? "Adjust the placement or status filter." : "Create a private block when approved public copy is ready."; return <div className="grid min-h-72 place-items-center px-6 py-12 text-center"><div className="max-w-md"><h3 className="text-lg font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500 font-medium">{copy}</p></div></div>; }
function placementLabel(value: SiteContentBlock["placement"]) { return value === "announcement" ? "Site-wide announcement" : "Homepage feature"; }
